drop /maprdb/json/tpcds/call_center
drop /maprdb/json/tpcds/catalog_page
drop /maprdb/json/tpcds/catalog_returns
drop /maprdb/json/tpcds/catalog_sales
drop /maprdb/json/tpcds/cust_temp
drop /maprdb/json/tpcds/customer
drop /maprdb/json/tpcds/customer_address
drop /maprdb/json/tpcds/customer_demographics
drop /maprdb/json/tpcds/date_dim
drop /maprdb/json/tpcds/household_demographics
drop /maprdb/json/tpcds/income_band
drop /maprdb/json/tpcds/inventory
drop /maprdb/json/tpcds/item
drop /maprdb/json/tpcds/promotion
drop /maprdb/json/tpcds/reason
drop /maprdb/json/tpcds/ship_mode
drop /maprdb/json/tpcds/store
drop /maprdb/json/tpcds/store_returns
drop /maprdb/json/tpcds/store_sales
drop /maprdb/json/tpcds/time_dim
drop /maprdb/json/tpcds/warehouse
drop /maprdb/json/tpcds/web_page
drop /maprdb/json/tpcds/web_returns
drop /maprdb/json/tpcds/web_sales
drop /maprdb/json/tpcds/web_site

create /maprdb/json/tpcds/call_center    
create /maprdb/json/tpcds/catalog_page   
create /maprdb/json/tpcds/catalog_returns
create /maprdb/json/tpcds/catalog_sales  
create /maprdb/json/tpcds/cust_temp      
create /maprdb/json/tpcds/customer       
create /maprdb/json/tpcds/customer_address 
create /maprdb/json/tpcds/customer_demographics
create /maprdb/json/tpcds/date_dim       
create /maprdb/json/tpcds/household_demographics
create /maprdb/json/tpcds/income_band    
create /maprdb/json/tpcds/inventory      
create /maprdb/json/tpcds/item
create /maprdb/json/tpcds/promotion      
create /maprdb/json/tpcds/reason         
create /maprdb/json/tpcds/ship_mode      
create /maprdb/json/tpcds/store
create /maprdb/json/tpcds/store_returns  
create /maprdb/json/tpcds/store_sales
create /maprdb/json/tpcds/time_dim       
create /maprdb/json/tpcds/warehouse      
create /maprdb/json/tpcds/web_page       
create /maprdb/json/tpcds/web_returns
create /maprdb/json/tpcds/web_sales      
create /maprdb/json/tpcds/web_site  
