SELECT
  O.O_ORDERPRIORITY,
  COUNT(*) AS ORDER_COUNT
FROM
  orders O
WHERE
  O.O_ORDERDATE >= DATE '1996-10-01'
  AND O.O_ORDERDATE < DATE '1996-10-01' + INTERVAL '3' MONTH
  AND 
  EXISTS (
    SELECT
      *
    FROM
      lineitem L
    WHERE
      L.L_ORDERKEY = O.O_ORDERKEY
      AND L.L_COMMITDATE < L.L_RECEIPTDATE
  )
GROUP BY
  O.O_ORDERPRIORITY
ORDER BY
  O.O_ORDERPRIORITY;
